---
name: plugin build

"on":
  push:
    branches-ignore: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: login ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: build
        run: |
          make --warn-undefined-variables PLUGIN_TAG=${GITHUB_REF##*/} push
